#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    # @todo Find out the causes for the build failures
    #buildExamples(bld)
    #buildTest(bld, 'TestOpener')
    buildTest(bld, 'TestPath')
    buildTest(bld, 'TestPathPart')
    buildTest(bld, 'TestPolicy')
    # buildTest(bld, 'TestRestriction')
    buildTest(bld, 'TestRestrictionStore')
    buildTest(bld, 'TestStream')

def buildExamples(bld):
    buildTestWithSources(bld, 'myrrh.log.policy.test.TestExamples',
                         'TestExamples.cpp File.cpp')

def buildTest(bld, file):
    name = 'myrrh.log.policy.test.' + file
    buildTestWithSources(bld, name, file + '.cpp')

def buildTestWithSources(bld, name, sources):
    bld.program(features='UnitTest', source=sources, target=name,
                use='myrrh.log.policy myrrh.file boost', lib='Advapi32',
                includes='../../../..')
