#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    buildExamples(bld)
    buildTest(bld, 'TestOpener')
    buildTest(bld, 'TestPath')
    buildTest(bld, 'TestPathPart')
    buildTest(bld, 'TestPolicy')
    buildTest(bld, 'TestRestriction')
    buildTest(bld, 'TestRestrictionStore')
    buildTest(bld, 'TestStream')

def buildExamples(bld):
    buildTestWithSources(bld, 'myrrh.log.policy.test.TestExamples',
                         'TestExamples.cpp File.cpp')

def buildTest(bld, file):
    name = 'myrrh.log.policy.test.' + file
    buildTestWithSources(bld, name, file + '.cpp')

def buildTestWithSources(bld, name, sources):
    bld.program(source=sources, target=name,
                use='myrrh.log.policy myrrh.file BOOST',
                includes='../../../..')
    bld(rule='src/log/policy/test/' + name, source=name)
