
* myrrh

myrrh is a logging library I implemented at around 2006-2007 so that I would have something to show when looking for work. I published it recently in GitHub for the same purpose.

Admittedly the library would benefit from a face-lift. It is written in C++98 and would probably look prettier with additions from C++11. Also I've learned a few things so I would do quite many things differently these days. Especially with unit tests. Let's see if I ever come around to do it.

** Build instructions

  1) Install [[http://www.python.org/][python]]
  2) Install [[http://code.google.com/p/waf/][waf]]
  3) Build from command line
     - on linux: waf configure build
     - on windows: waf configure build_debug build_release

** Status of the project

If you find the project useful, feel free to use it. The code is published with boost 1.0 license. But be warned that the library has not ever been used in production code. There is no real-life knowledge of stability nor of performance.

** Documentation

There is fairly large document that describes the entire myrrh library. It mostly concentrates on trying to sell the library instead of actually documenting it. It might be of some use though.

You can find the documentation under in docs/MyrrhDocumentation.org.
