#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    buildTest(bld, 'TestCatchExceptions')
    buildTest(bld, 'TestCopyIf')
    buildTest(bld, 'TestGenerateOutput')
    buildTest(bld, 'TestPrint')
    buildTest(bld, 'TestProgressTimer')
    buildTest(bld, 'TestRandomString')
    buildTest(bld, 'TestRepeat')
    buildTest(bld, 'TestStream')
    buildTest(bld, 'TestTime')

def buildTest(bld, file):
    name = 'myrrh.util.test.' + file
    bld.program(features='UnitTest', source=file + '.cpp',
                target=name, use='myrrh.util myrrh.file myrrh.data.test BOOST',
                includes='../../..')
