#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(features='UnitTest', source='TestFiles.cpp',
                target='myrrh.data.test.test',
                use='myrrh.data.test boost', includes='../../../..')
