#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.stlib(source='Copy.cpp PositionScanner.cpp ReadOnly.cpp Resizer.cpp ' +
                     'SafeModify.cpp Temporary.cpp',
              target='myrrh.file', includes='../..')
    #bld.recurse('test')
